export interface LoanTermsInterface{
AddedBy?:string
AIRA?:number
ApplicationID?:number
BackEnd?:number
Comments?:string
DateAdded?:Date
Deleted?:boolean
DownPayment?:number
FrontEnd?:number
HamiltonFee?:number
ID?:bigint
LastUpdated?:Date
LoanAmount?:number
LoanOriginationFee?:number
LoanTerm?:number
LoanTermPaymentAmount?:number
LoanTermsGUID?:number
LoanTermType?:string
NetCheck?:number
NetFinanced?:number
OfferType?:string
PTI?:number
APR?:number
}
