export interface UserActiveAccountsInterface {
  Active: boolean;
  Address: string;
  Adress2: string | null;
  ApplicationGUID: string;
  ApplicationID: number;
  AmountFinanced:number;
  CellPhone: string;
  City: string;
  Country: string;
  DateAdded: string;
  DealerID: number;
  Deleted: boolean;
  DLNumber: string;
  DLState: string;
  DOB: Date;
  EmailAddress: string;
  FirstName: string;
  ID: number;
  LastName: string;
  LastUpdate: string;
  MiddleName: string;
  Password: string;
  PostalCode: string;
  ProfileGUID: string;
  ProfileTypeID: number;
  State: string;
  TAXID: string;
  VehicleColor: string;
  VehicleEngine: string;
  VehicleHorsePower: string;
  VehicleMake: string;
  VehicleMileage: number;
  VehicleModel: string;
  VehicleTransmission: string;
  VehicleYear: number;
  PurchasePrice:number;
  HowLong:string;
  SalesTax:number;
  TLCTrackerFee:number;
}
